#!/bin/bash
# ./examples/utils_stdout_colors.sh
# Just for tests, should not be include.
. ../utils/utils_stdout_colors.sh

echo "# Reset"
echo -e "Color_Off:         ${Color_Off}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# Regular Colors"
echo -e "Black:             ${Black}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Red:               ${Red}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Green:             ${Green}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Yellow:            ${Yellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Blue:              ${Blue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Purple:            ${Purple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "Cyan:              ${Cyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "White:             ${White}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# Bold"
echo -e "BBlack:            ${BBlack}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BRed:              ${BRed}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BGreen:            ${BGreen}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BYellow:           ${BYellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BBlue:             ${BBlue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BPurple:           ${BPurple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BCyan:             ${BCyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BWhite:            ${BWhite}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# Underline"
echo -e "UBlack:            ${UBlack}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "URed:              ${URed}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UGreen:            ${UGreen}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UYellow:           ${UYellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UBlue:             ${UBlue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UPurple:           ${UPurple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UCyan:             ${UCyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "UWhite:            ${UWhite}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# Background"
echo -e "On_Black:          ${On_Black}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Red:            ${On_Red}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Green:          ${On_Green}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Yellow:         ${On_Yellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Blue:           ${On_Blue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Purple:         ${On_Purple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_Cyan:           ${On_Cyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_White:          ${On_White}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# High Intensty"
echo -e "IBlack:            ${IBlack}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IRed:              ${IRed}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IGreen:            ${IGreen}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IYellow:           ${IYellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IBlue:             ${IBlue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IPurple:           ${IPurple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "ICyan:             ${ICyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "IWhite:            ${IWhite}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# Bold High Intensty"
echo -e "BIBlack:            ${BIBlack}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIRed:              ${BIRed}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIGreen:            ${BIGreen}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIYellow:           ${BIYellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIBlue:             ${BIBlue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIPurple:           ${BIPurple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BICyan:             ${BICyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "BIWhite:            ${BIWhite}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "# High Intensty backgrounds"
echo -e "On_IBlack:            ${On_IBlack}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IRed:              ${On_IRed}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IGreen:            ${On_IGreen}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IYellow:           ${On_IYellow}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IBlue:             ${On_IBlue}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IPurple:           ${On_IPurple}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_ICyan:             ${On_ICyan}Lorem ipsum dolor sit amet${Color_Off}"
echo -e "On_IWhite:            ${On_IWhite}Lorem ipsum dolor sit amet${Color_Off}"
echo ""
echo "Done."
